version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: basketball-system-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - basketball_postgres_data:/var/lib/postgresql/data

  player-service:
    build:
      context: ./player-service
      dockerfile: Dockerfile

    container_name: player-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8081
    depends_on:
      - postgres
    restart: unless-stopped

  team-service:
    build:
      context: ./team-service
      dockerfile: Dockerfile
    container_name: team-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8082
    depends_on:
      - postgres
      - player-service
    restart: unless-stopped

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile
    container_name: match-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8083
    depends_on:
      - postgres
      - player-service
      - team-service
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      PLAYER_SERVICE_URL: http://player-service:8081
      TEAM_SERVICE_URL: http://team-service:8082
      MATCH_SERVICE_URL: http://match-service:8083
    depends_on:
      - player-service
      - team-service
      - match-service
    restart: unless-stopped

volumes:
  basketball_postgres_data: