server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: player-service
          uri: http://player-service:8081
          predicates:
            - Path=/api/players/**

        - id: team-service
          uri: http://team-service:8082
          predicates:
            - Path=/api/teams/**

        - id: match-service
          uri: http://match-service:8083
          predicates:
            - Path=/api/matches/**

logging:
  level:
    com.example.apigateway: DEBUG
    org.springframework.web: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
